### ISSUE TITLE
add link to blog

### ISSUE THREAD

**Issue by Sammeeey** [ewainy/myblog#5]
- [ ] in README
- [x] in *About* settings of myblog repo (upper right)

... as soon as it's online?!

**Comment by ewainy** [comment]
> * [ ]  in README
> * [ ]  in _About_ settings of myblog repo (upper right)
> 
> ... as soon as it's online?!

Thank you Sam for creating this issue, great suggestions that will definitely be added to this project!! I didnt even think to add it to 'About' what a good idea 😊💡

**Comment by ewainy** [comment]
Hey @Sammeeey I've done the 2nd task and added link to 'About' did you fancy doing the first task or should I share with someone in EddieHub as a good first issue?

**Comment by Sammeeey** [comment]
I wouldn't say I've fancied.
But if you assign it to me, I'll do it 😊 - if you think it makes sense.
Maybe you are already okay with the description link in the "About" section!?🤔

**Comment by ewainy** [comment]
Lol I can't make decisions 🙈 I'm happy either way 😊

**Comment by Sammeeey** [comment]
Then I'd suggest, let's don't mess with the readme for now and close the issue.
For now the basic info and link exist in the "About".
Let's don't be redundant.
If there comes a good reason to be redundant - hence to include the info in the readme too - then it's not going to be a big deal.

**Comment by ewainy** [comment]
Thank you Sam, great advice 😊💖
